// export name is the object key asociated with container/component you want rendere
export about from '../components/About/About'
export contact from '../components/Contact/Contact'
export gritfund from '../components/Gritfund/Gritfund'
export home from '../components/Home/Home'
export page from '../components/Page'
export profile from './Profile'
export programs from '../components/Programs/Programs'
export projects from '../components/Projects/Projects'
export resources from '../components/Resources/Resources'
export scroll from '../components/Scroll/Scroll'
export speakers from '../components/Speakers/Speakers'
export support from '../components/Support/Support'
export shop from '../components/Shop/Shop'
export visit from '../components/Visit/Visit'
